### ISSUE TITLE
Вопрос о POW и каптче

### ISSUE THREAD

**Issue by sergei-bondarenko** [Karasiq/nanoboard#2]
Можешь в двух словах объяснить, как работает POW и выбор каптчи в наноборде? И ещё такой вопрос, эту идею про совмещение капчти с POW (а не только лишь использование POW) ты откуда-то заимствовал или сам придумал?

**Comment by Karasiq** [comment]
Изначально это было в клиенте на C#, и я скопировал оттуда. Не знаю что с ним сейчас.
