### ISSUE TITLE
atob(не_base64) стопорит скрипт Throw error'ом

### ISSUE THREAD

**Issue by username1565** [Karasiq/nanoboard#6]
Посты, содержащие `[xmg=не_base64]`, `[img=не_бейс64]`, `[file]не_base64[/file]`,
и возможно ещё что-то - ложат наноборду.
Они - не отображаются, и их нельзя удалить из-за того,
что throw-error останавливает выполнение скрипта.

Этот баг уже был описан [здесь](https://github.com/Karasiq/nanoboard/issues/5#issuecomment-460510875), и [здесь](https://github.com/Karasiq/nanoboard/issues/5#issuecomment-462182553)

Я использую [nanoboard-portable-1.3.2.zip](https://github.com/Karasiq/nanoboard/releases/tag/v1.3.2) и для себя, я решил этот вопрос следующим образом:
1. Запустил наноборду, прогрузил всё, безуспешно попытался зайти в категорию **test**.
Там внутри - посты с тегами, без бейса.
2. Пошёл в консоль браузера (клавиша `F12`), увидел имя скрипта, номер строки и символ.
3. Пошёл в папку `\lib\`
2. Распаковал там `jar-файл` - `nanoboard-server.jar` , используя `7-zip`.
2. Пошёл в папку: `\nanoboard-portable-1.3.2\lib\nanoboard-server\webapp\scripts\0dd95fa0-a4f8-4117-bdf9-6fba998771b3.js`
3. Нашёл там один единственный вызов функции `atob` в строке `1538`, на символе `75`:
```javascript
h=Gf(Hf()).atob(d);
```
4. Заменил всю функцию на это:
```javascript


//check is base64 without throw error
function isBase64(str) {//return true, or false
    if(str==='' || str.trim()===''){return false;}//if string is empty or not contains base64 characters
    try {
        return btoa(atob(str)) == str; //true if base64
    } catch (err) {
        return false;
    }
}
function vA(h,d,a){
	h=(isBase64(d)) ? Gf(Hf()).atob(d) : d;
	h=lF(hd(),h);d=[];for(var b=0,c=h.b.length;b<c;)d.push(h.b[b]<<24>>24),b=1+b|0;return jv(0,n(G(Bd),d),a)
}

```
5. Сохранил `0dd95fa0-a4f8-4117-bdf9-6fba998771b3.js`,
потом выключил наноборду,
и обновил `JAR-файл`, как `7z-архив`. Просто добавил этот файл, используя `7z`.
6. Запустил наноборду снова, двойным кликом по nanoboard.bat,
но я всё ещё видел `atob-error` в консоли.
7. Я также видел старый скрипт `0dd95fa0-a4f8-4117-bdf9-6fba998771b3.js`, без исправлений,
в кэше браузера `Google Chrome`.
8. Поэтому страница наноборды - была обновлена, с обновлением кэша хрома `(Ctrl+Shift+R)`
9. Теперь ошибки нет, посты все видно, и их можно **удалить**...

Вот эти посты:

> # [946d50e33c413a93d7c963424e0846d9](http://127.0.0.1:7347/#946d50e33c413a93d7c963424e0846d9)
> > `//          $('#result').text('[xmg='+res.substring(res.indexOf(',')+1)+']');`
> * throw-error функции atob : `[xmg=не_base64]`
> > `$('#result').text('[file name="'+file.name+'" type="'+file.type+'"]'+res.substring(res.indexOf(',')+1)+'[/file]');`
> * throw-error функции atob: `[file]не_base64[/file]`
> # [c19a06c128f78e5946014883bc018dd9](http://127.0.0.1:7347/#c19a06c128f78e5946014883bc018dd9)
> > `'[file name="filename.extension" type="mime-type"]BASE64-CONTENT[/file]'`
> * throw-error функции atob: `[file]не_base64[/file]`
> # [4dcf53a58e839e8fddce6959222ed675](http://127.0.0.1:7347/#4dcf53a58e839e8fddce6959222ed675)

Просьба перепаковать [nanoboard-portable-1.3.2.zip](https://github.com/Karasiq/nanoboard/releases/tag/v1.3.2) потому что контейнер с этими постами - висит на доброчане.

**Comment by AHOHNMYC** [comment]
Перевожу с русского на русский.
Добавь обработку исключений вот [тут](https://github.com/Karasiq/nanoboard/blob/master/frontend/src/main/scala/com/karasiq/nanoboard/frontend/utils/Blobs.scala#L32).

**Comment by username1565** [comment]
bump

**Comment by username1565** [comment]
bump

**Comment by username1565** [comment]
Бамп

**Comment by username1565** [comment]
Бабамп!
